### ISSUE TITLE
Feature request: DragDropNormalizer with acrylic effect

### ISSUE THREAD

**Issue by Dhyfer1** [krlvm/DragDropNormalizer#1]
Hi @krlvm 

The semi-transparent effect of the overlay looks good, but I think with an acrylic effect it would look much better in Win11 (as your AcrylicMenus repository does). Please, could you add acrylic for DragDropNormalizer? 

Another thing, when I select a file/folder and drag it, one second later the file/folder icon appears inside the overlay, no matter what view the file explorer is in (details, list, content etc). Can you correct this delay?

**Comment by krlvm** [comment]
This delay has always been since Windows Vista, when the overlay was introduced, and is caused by reading file icon being too slow.
They have done something, so its performance even worse in Windows 11 22H2.

Acrylic does not work that way, so it is not possible

**Comment by Dhyfer1** [comment]
> This delay has always been since Windows Vista, when the overlay was introduced, and is caused by reading file icon being too slow. 

Oh. That's okay, I'll have to get used to it.

> Acrylic does not work that way, so it is not possible

So, DragDropNormalizer can't have an acrylic effect? 🙁 That's bad news, otherwise it would look great, don't you think? I hope you can find a way to do it some day.
